import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';

const repoTokensUrl = new URL('../../design-tokens.css', import.meta.url);
const outputUrl = new URL('../src/tokens.generated.ts', import.meta.url);
const css = await readFile(repoTokensUrl, 'utf8');
const darkBlock = css.match(/\[data-theme="dark"\]\s*\{(?<body>[\s\S]*?)\}/)?.groups?.body;

if (!darkBlock) {
  throw new Error(`Dark theme block not found in ${fileURLToPath(repoTokensUrl)}`);
}

const declarations = new Map(
  [...darkBlock.matchAll(/--(?<name>ag-[\w-]+)\s*:\s*(?<value>#[0-9A-Fa-f]{6})\s*;/g)].map(
    ({groups}) => [groups.name, groups.value.toUpperCase()],
  ),
);

const required = ['ag-brand', 'ag-bg', 'ag-surface', 'ag-border', 'ag-text', 'ag-text-muted', 'ag-allow', 'ag-ask', 'ag-deny'];
for (const token of required) {
  if (!declarations.has(token)) {
    throw new Error(`Required token --${token} not found in ${fileURLToPath(repoTokensUrl)}`);
  }
}

const token = (name) => declarations.get(`ag-${name}`);
const generated = `// Generated by scripts/generate-theme.mjs. Do not edit.\nexport const C = {\n  brand: '${token('brand')}',\n  brandStrong: '${token('brand')}',\n  brandLogo: '${token('brand')}',\n  bg: '${token('bg')}',\n  raised: '${token('surface')}',\n  surface: '${token('surface')}',\n  border: '${token('border')}',\n  text: '${token('text')}',\n  muted: '${token('text-muted')}',\n  allow: '${token('allow')}',\n  ask: '${token('ask')}',\n  deny: '${token('deny')}',\n} as const;\n`;

await writeFile(outputUrl, generated, 'utf8');
