#![no_main]
use libfuzzer_sys::fuzz_target;
use algo_policy::{Engine, PolicyDecision, Profile};

// Cargo fuzz entry: `fn main` is generated by `libfuzzer_sys::fuzz_target!(|data: &[u8]| { if let Ok(s) = std::str::from_utf8(data) { let _ = target_fn(s); } })`.
// For `cargo check` without fuzzing, a dummy `fn main` is provided at the bottom via `#[cfg(not(fuzzing))]`.

// Fuzz `algo_policy::Engine::evaluate` with arbitrary command string.
// Invariants (P1-09, AGENTS.md:6):
// - must never panic (all regex paths use OnceLock compiled patterns, no unwrap on input)
// - must return Deny or Abstain only, never Allow on arbitrary input (hard-deny is regex match, otherwise abstain -> ask)
// - on error/timeout/parse-fail the pipeline maps to ASK, never ALLOW (fail-safe)
fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        let engine = Engine::new();

        // Primary profile: Balanced (the default harness profile)
        let decision = engine.evaluate(s, Profile::Balanced);
        // Policy engine is deny-or-abstain only - Allow is not a valid return for evaluate().
        // This asserts the fail-safe: no arbitrary input can produce Allow.
        assert!(
            !matches!(decision, PolicyDecision::Allow { .. }),
            "policy evaluate must never return Allow for fuzz input"
        );
        // Touch decision fields to ensure no panic on later formatting.
        match &decision {
            PolicyDecision::Deny { rule_id, reason } => {
                let _ = rule_id.len();
                let _ = reason.len();
            }
            PolicyDecision::Abstain => {
                // Abstain maps to ASK in the pipeline (fail-safe) - prove it is not Allow.
            }
            PolicyDecision::Allow { .. } => unreachable!("checked above"),
        }

        // Prove all profiles are also fail-safe (never override hard-deny, never produce Allow)
        let d_strict = engine.evaluate(s, Profile::Strict);
        assert!(!matches!(d_strict, PolicyDecision::Allow { .. }));
        let d_fast = engine.evaluate(s, Profile::Fast);
        assert!(!matches!(d_fast, PolicyDecision::Allow { .. }));

        // Also prove Default impl doesn't panic
        let default_engine = Engine::default();
        let _ = default_engine.evaluate(s, Profile::Balanced);
    }
});

// Dummy fn main for `cargo check` without `--cfg fuzzing`; real main is generated by libfuzzer_sys when fuzzing.
#[cfg(not(fuzzing))]
#[allow(dead_code)]
fn main() {}
