#![no_main]
use libfuzzer_sys::fuzz_target;

// Fuzz `algo_redact::redact` on arbitrary &str.
// Invariants (AGENTS.md:6):
// - must never panic (no unwrap on input; regexes precompiled via OnceLock)
// - idempotent: redact(redact(x)) == redact(x)
// - no pattern survives: a second pass finds nothing
// Callers map any redact failure to ASK, never ALLOW (proves_ask_on_no_redact).
// Cargo fuzz entry: `fn main` is generated by `libfuzzer_sys::fuzz_target!(|data: &[u8]| { if let Ok(s) = std::str::from_utf8(data) { let _ = target_fn(s); } })`.
// For `cargo check` without fuzzing, a dummy `fn main` is provided at the bottom via `#[cfg(not(fuzzing))]`.
fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        let (masked1, _) = algo_redact::redact(s);
        // Touch findings to ensure Debug on arbitrary content doesn't panic.
        let _ = masked1.len();
        // Idempotence: second pass must be a fixpoint.
        let (masked2, findings2) = algo_redact::redact(&masked1);
        assert_eq!(masked1, masked2, "redact must be idempotent for fuzz input");
        // No pattern survives the first pass.
        assert!(
            findings2.is_empty(),
            "no redact findings may survive a second pass"
        );
    }
});

// Dummy fn main for `cargo check` without `--cfg fuzzing`; real main is generated by libfuzzer_sys when fuzzing.
#[cfg(not(fuzzing))]
#[allow(dead_code)]
fn main() {}
