#![no_main]
use algo_adapter_claude::parse::{parse_hook, proves_ask_on_parse_fail};
use algo_types::Action;
use libfuzzer_sys::fuzz_target;

// Cargo fuzz entry: `fn main` is generated by `libfuzzer_sys::fuzz_target!(|data: &[u8]| { if let Ok(s) = std::str::from_utf8(data) { let _ = target_fn(s); } })`.
// For `cargo check` without fuzzing, a dummy `fn main` is provided at the bottom via `#[cfg(not(fuzzing))]`.

// Fuzz `algo_adapter_claude::parse::parse_hook` on arbitrary string/bytes.
// Invariants (P1-07, AGENTS.md:6):
// - must never panic on any input (no unwrap/expect, all fallible paths return ParseError)
// - on Err the caller maps to ASK via `proves_ask_on_parse_fail` (never Allow/Deny)
// - proves_ask_on_parse_fail must always produce Action::Ask with source Fallback, never Allow
fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        let res = parse_hook(s);
        match res {
            Ok(ev) => {
                // Shell-only P1: tool_kind is always Shell
                assert!(ev.is_shell());
                let _ = ev.command.len();
                let _ = ev.cwd.len();
                let _ = ev.session_id.len();
                // Touch raw JSON to ensure no panic on debug
                let _ = format!("{:?}", ev.raw);
            }
            Err(e) => {
                // Fail-safe: any parse error maps to ASK, never Allow, via proves_ask_on_parse_fail
                let decision = proves_ask_on_parse_fail(e.clone());
                assert_eq!(
                    decision.action,
                    Action::Ask as i32,
                    "proves_ask_on_parse_fail must be Ask, got {}",
                    decision.action
                );
                assert_ne!(decision.action, Action::Allow as i32);
                // Allow alternate entry with trace_id also preserves ask
                let d2 = algo_adapter_claude::parse::proves_ask_on_parse_fail_with_trace(
                    e,
                    "fuzz-trace",
                );
                assert_eq!(d2.action, Action::Ask as i32);
                assert_eq!(d2.trace_id, "fuzz-trace");
                assert_eq!(d2.confidence_0_1, 0.0);
            }
        }
    }
});

// Dummy fn main for `cargo check` without `--cfg fuzzing`; real main is generated by libfuzzer_sys when fuzzing.
#[cfg(not(fuzzing))]
#[allow(dead_code)]
fn main() {}
