#![no_main]
use libfuzzer_sys::fuzz_target;

// Fuzz `algo-shell-analysis::parse::parse` on arbitrary &str.
// Invariant: must never panic. On Err(ParseError) the pipeline maps to ASK (fail-safe, never Allow).
// See `core/crates/shell-analysis/src/parse.rs::parse` and AGENTS.md:6 proves_ask_on_* rule.
// Cargo fuzz entry: `fn main` is generated by `libfuzzer_sys::fuzz_target!(|data: &[u8]| { if let Ok(s) = std::str::from_utf8(data) { let _ = target_fn(s); } })`.
// For `cargo check` without fuzzing, a dummy `fn main` is provided below via `#[cfg(not(fuzzing))]`.
fuzz_target!(|data: &[u8]| {
    if let Ok(s) = std::str::from_utf8(data) {
        // Call the crate's parse entry point - this exercises tree-sitter parsing,
        // command extraction, and the fallback split path.
        let res = algo_shell_analysis::parse::parse(s);
        match res {
            Ok(cmd) => {
                // Touch fields to ensure Debug/Clone and later consumers don't panic on arbitrary content.
                let _ = format!("{:?}", cmd);
                // ParsedCmd { commands, redirects, pipes, subshells, env_assigns, raw }
                let _ = cmd.raw.len();
                let _ = cmd.commands.len();
                let _ = cmd.pipes;
                let _ = cmd.subshells;
                for c in &cmd.commands {
                    let _ = c.bin.len();
                    let _ = c.args.len();
                    let _ = c.flags.len();
                }
            }
            Err(e) => {
                // Fail-safe: parse error must map to ASK, never ALLOW.
                // In the pipeline this is `Decision::Ask` via `ask_on_error` / `to_ask_on_error`.
                // Here we just prove the error is displayable and not an allow.
                let msg = format!("{}", e);
                let _ = msg.len();
                // No panic, no allow - caller would map to ask.
            }
        }
    }
});

// Dummy fn main for `cargo check` without `--cfg fuzzing`; real main is generated by libfuzzer_sys when fuzzing.
#[cfg(not(fuzzing))]
#[allow(dead_code)]
fn main() {}
